server:
  port: 443
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store-password: 123456
    key-store: keystore.p12
spring:
  thymeleaf:
    cache: false
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.session.SessionAutoConfiguration
custom:
  site:
    baseUrl: https://localhost